name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ocaml-compiler:
          - 4.14.x
          - 5.0.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install locally
        run: opam install . --deps-only --with-test
      - name: Build locally
        run: opam exec -- dune build
      - name: Run tests locally
        run: opam exec -- dune runtest
